version: '3'

services:
    site:
      build:
       context: .
       dockerfile: nginx.dockerfile
      container_name: nginx
      restart: always
      ports:
       - "8888:80"
      volumes:
       - ./src:/var/www/html:delegated
      depends_on:
       - php
       - db

    php:
     build:
       context: .
       dockerfile: php.dockerfile
     container_name: php
     restart: always
     volumes:
       - ./src:/var/www/html:delegated
     expose:
       - "9000"
   
    db:
      image: mysql:8.0
      container_name: DATABASE
      restart: always
      volumes:
       - ./mysql-data:/var/lib/mysql
       - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      environment:
       MYSQL_ROOT_PASSWORD: 'password'
       MYSQL_DATABASE: 
      expose:
       - "3306"

    PMA:
      depends_on:
       - db
      image: phpmyadmin/phpmyadmin
      container_name: PMA
      restart: always
      ports:
       - '8081:80'
      environment:
        PMA_HOST: db
